# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST {{host}}/channels
Content-Type: application/json

{
  "reload": true
}

###

POST {{host}}/channels
Content-Type: application/json

{
  "reload": false
}

###

POST {{host}}/channels
Content-Type: application/json

{
  "regex": ".*"
}

###
POST {{host}}/channels
Content-Type: application/json

{
  "reload": false,
  "regex": "twlha"
}

###

GET {{host}}/params/backends

###

GET {{host}}/params/aggregations

###

GET {{host}}/params/configfields

###

GET {{host}}/params/eventfields

###

GET {{host}}/params/ordering

###

GET {{host}}/params/responseformat

###

GET {{host}}/params/compression

###

GET {{host}}/params/backends/byid

#### NOT YET SUPPORTED
#
#GET {{host}}/params/queryfields
#Content-Type: application/json
#
####
#
#GET {{host}}/channels/hash

###
# Response: [{"backend":"sf-archiverappliance","channels":[{"source":"sf-cagw-arch.psi.ch","backend":"sf-archiverappliance","unit":"A","type":"float64","shape":[1],"name":"CR0808:CURRENT-3-3"}]}]

POST {{host}}/channels/config
Content-Type: application/json

{
  "regex": "CR0808:CURRENT-3-3"
}

###

POST {{host}}/channels/config
Content-Type: application/json

{
  "regex": ".*"
}

###

POST {{host}}/query
Content-Type: application/json

{
  "channels": [
    "SLG-LSCP3-FNS:CH7:VAL_GET"
  ],
  "range": {
    "startDate": "2019-10-03T10:00:00.000000000Z",
    "endDate": "2019-10-03T10:05:00.000000000Z"
  }
}

###

POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2019-07-08T01:00:00.000Z",
    "endDate": "2019-07-09T01:00:00.000Z"
  },
  "channels": [
    {
      "name": "SINEG01-DWCM170:TIME",
      "backend": "sf-archiverappliance"
    },
    {
      "name": "SINLH01-DBAM010:EOM1_T1",
      "backend": "sf-archiverappliance"
    },
    {
      "name": "S10BC01-DBAM070:EOM1_T1",
      "backend": "sf-archiverappliance"
    }
  ]
}

###

# test of a string channel that caused some troubles some time ago
POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2019-07-29T06:00:00.000Z",
    "endDate": "2019-08-02T06:00:00.000Z"
  },
  "channels": [
    {
      "name": "S30CB04-RILK:STR-DESC-CURRENT-LOG",
      "backend": "sf-archiverappliance"
    }
  ]
}

###
# with expanded channel list
POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2019-11-14T10:15:30.786Z",
    "endDate": "2019-11-14T10:16:30.786Z"
  },
  "channels": [
    {
      "name": "S10CB01-RBOC-DCP10:FOR-AMPLT",
      "backend": "sf-databuffer"
    }
  ]
}

###

POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2020-10-14T13:00:00.000Z",
    "endDate": "2020-10-14T13:01:00.000Z"
  },
  "channels": [
    {
      "name": "TWLHA2-CVME-ILK:SYS_CPU_LOAD",
      "backend": "twlha-archiverappliance"
    }
  ]
}

###

## Test with no Z or timezone
POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2020-10-14T13:00:00.000",
    "endDate": "2020-10-14T13:01:00.000"
  },
  "channels": [
    {
      "name": "TWLHA2-CVME-ILK:SYS_CPU_LOAD",
      "backend": "twlha-archiverappliance"
    }
  ]
}

###

# Test long range with aggregation
POST {{host}}/query
Content-Type: application/json

{
  "range": {
    "startDate": "2020-10-14T13:00:00.000",
    "endDate": "2020-10-14T13:10:00.000"
  },
  "aggregation": {
    "aggregationType": "value",
    "aggregations": [
      "min",
      "mean",
      "max"
    ],
    "nrOfBins": 2
  },
  "channels": [
    {
      "name": "TWLHA2-CVME-ILK:SYS_CPU_LOAD",
      "backend": "twlha-archiverappliance"
    }
  ]
}

###

POST {{host}}/query
Content-Type: application/json

## if changing 1604419588.316 to 1604419688.316 all is ok
{
  "channels": [
    {
      "backend": "twlha-archiverappliance",
      "name": "TWLHA2-CVME-ILK:SYS_CPU_LOAD"
    }
  ],
  "range": {
    "startSeconds": 1604419408.316,
    "endSeconds": 1604419588.316
  },
  "eventFields": [
    "globalMillis",
    "pulseId",
    "value",
    "eventCount"
  ],
  "aggregation": {
    "aggregationType": "value",
    "aggregations": [
      "max",
      "mean",
      "min"
    ],
    "nrOfBins": 512
  }
}


###

POST {{host}}/query
Content-Type: application/json

{"response":{"format":"json"},"range": { "startSeconds" : "1641918710", "endSeconds" : "1642005110"},"channels": [ {"name":"SLAAR01-TLSY-EPL:JITTERMON", "backend" : "sf-archiverappliance" }],"fields":["channel","globalSeconds","value"], "aggregation": {"aggregationType":"value", "aggregations":["min","mean","max"], "durationPerBin" : "PT1S"}}

###

POST {{host}}/query
Content-Type: application/json

//{"response":{"format":"json"},"range": { "startSeconds" : "1641918710", "endSeconds" : "1642005110"},"channels": [ {"name":"SLAAR01-TLSY-EPL:JITTERMON", "backend" : "sf-archiverappliance" }],"fields":["channel","globalSeconds","value"]}
//{"response":{"format":"json"},"range": { "startSeconds" : "1642066635", "endSeconds" : "1642070235"},"channels": [ {"name":"SINBC02-DDRM005:DOSE-OP" }],"fields":["channel","globalSeconds","value"], "aggregation": {"aggregationType":"value", "aggregations":["min","mean","max"], "durationPerBin" : "PT1S"}}
{"response":{"format":"json"},"range": { "startSeconds" : "1642066635", "endSeconds" : "1642070235"},"channels": [ {"name":"SINBC02-DDRM005:DOSE-OP" }],"fields":["channel","globalSeconds","value"], "aggregation": {"aggregationType":"value", "aggregations":["min","mean","max"], "nrOfBins" : 500}}

###

POST {{host}}/query
Content-Type: application/json

{
  "channels": [
    "SATUN06-UIND030:FELPHOTENE"
  ],
  "range": {
    "startDate": "2021-03-31T22:00:00.000000000Z",
    "endDate": "2021-04-30T22:00:00.000000000Z"
  }
}

###

POST {{host}}/query
Content-Type: application/json

{
  "channels": [
    "SARUN:FELPHOTENE"
  ],
  "range": {
    "startDate": "2021-03-31T22:00:00.000000000Z",
    "endDate": "2021-04-30T22:00:00.000000000Z"
  }
}

###

POST {{host}}/query
Content-Type: application/json

{"channels":[{"name":"SIN-TIMAST-TMA:Bunch-1-Appl-RB","backend":"sf-archiverappliance"}],"range":{"startDate":"2021-03-31T22:00:00.000Z","endDate":"2021-04-30T22:00:00.000Z","startExpansion":false,"endExpansion":false},"eventFields":["globalMillis","value","eventCount"],"aggregation":{"aggregations":["min","mean","max"],"nrOfBins":500}}